"""numba-utils: high-performance building blocks for Numba."""

from numba_utils import diagnostics, testing
from numba_utils._config import config, configure
from numba_utils.algorithms import (
    argmax2,
    counting_sort,
    fast_argpartition,
    insertion_sort,
    nth_element,
    partial_sort,
    quickselect,
    radix_sort,
    topk,
)
from numba_utils.arrays import (
    bincount,
    binary_search,
    cumulative_sum,
    fast_clip,
    histogram,
    lower_bound,
    normalize,
    rolling_mean,
    rolling_sum,
    unique_sorted,
    upper_bound,
)
from numba_utils.collections import (
    BitSet,
    FixedQueue,
    ObjectPool,
    PriorityQueue,
    RingBuffer,
    SparseSet,
    Stack,
    counter,
    typed_defaultdict,
)
from numba_utils.decorators import (
    boundscheck,
    cached_njit,
    njit_fast,
    njit_parallel,
)
from numba_utils.parallel import (
    parallel_histogram,
    parallel_prefix_sum,
    parallel_reduce,
    parallel_sum,
    parallel_topk,
)
from numba_utils.profiling import (
    BenchmarkResult,
    ComparisonResult,
    TimingStats,
    benchmark,
    compare,
    compile_stats,
    compile_time,
    warmup,
)
from numba_utils.random import (
    alias_draw,
    alias_sample,
    alias_setup,
    choice,
    permutation,
    reservoir_sampling,
    seed,
    shuffle,
    weighted_sampling,
)

__version__ = "0.1.2"

__all__ = [
    "BenchmarkResult",
    "BitSet",
    "ComparisonResult",
    "FixedQueue",
    "ObjectPool",
    "PriorityQueue",
    "RingBuffer",
    "SparseSet",
    "Stack",
    "TimingStats",
    "alias_draw",
    "alias_sample",
    "alias_setup",
    "argmax2",
    "benchmark",
    "bincount",
    "binary_search",
    "boundscheck",
    "cached_njit",
    "choice",
    "compare",
    "compile_stats",
    "compile_time",
    "config",
    "configure",
    "counter",
    "counting_sort",
    "cumulative_sum",
    "diagnostics",
    "fast_argpartition",
    "fast_clip",
    "histogram",
    "insertion_sort",
    "lower_bound",
    "njit_fast",
    "njit_parallel",
    "normalize",
    "nth_element",
    "parallel_histogram",
    "parallel_prefix_sum",
    "parallel_reduce",
    "parallel_sum",
    "parallel_topk",
    "partial_sort",
    "permutation",
    "quickselect",
    "radix_sort",
    "reservoir_sampling",
    "rolling_mean",
    "rolling_sum",
    "seed",
    "shuffle",
    "testing",
    "topk",
    "typed_defaultdict",
    "unique_sorted",
    "upper_bound",
    "warmup",
    "weighted_sampling",
]
